const ADD_DATA = "ADD_DATA";
const DELETE_DATA = "DELETE_DATA";
const ADD_NAME = "ADD_NAME";
const ADD_EMAIL = "ADD_EMAIL";
const ADD_PHOTO = "ADD_PHOTO";

export default { ADD_DATA, DELETE_DATA, ADD_NAME, ADD_EMAIL, ADD_PHOTO };